jobs:
- job: Linux
  container: nventive/wasm-build:1.4.1

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      sudo chmod -R 777 /emsdk
      cd /emsdk
      sudo ./emsdk activate sdk-1.38.31-64bit

    displayName: 'Setup Enscripten'

  - bash: |
      chmod +x scripts/wasm-uitest-run.sh
      scripts/wasm-uitest-run.sh

    env:
      GIT_TARGETBRANCH: "$(System.PullRequest.TargetBranch)"
      GIT_SOURCEBRANCH: "$(Build.SourceBranch)"
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

    displayName: 'Running build'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/source/SkiaSharpSample/SkiaSharpSample.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/skiasharp-wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false
      
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunTitle: 'WebAssembly Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.sourcesdirectory)/scripts/TestResult.xml'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: skiasharp-aot-drop
      ArtifactType: Container
